name:flutterui
description:AnewFlutterproject.
#Thefollowinglinepreventsthepackagefrombeingaccidentallypublishedto
#pub.devusing`flutterpubpublish`.Thisispreferredforprivatepackages.
publish_to:'none'#Removethislineifyouwishtopublishtopub.dev

#Thefollowingdefinestheversionandbuildnumberforyourapplication.
#Aversionnumberisthreenumbersseparatedbydots,like1.2.43
#followedbyanoptionalbuildnumberseparatedbya+.
#Boththeversionandthebuildernumbermaybeoverriddeninflutter
#buildbyspecifying--build-nameand--build-number,respectively.
#InAndroid,build-nameisusedasversionNamewhilebuild-numberusedasversionCode.
#ReadmoreaboutAndroidversioningathttps://developer.android.com/studio/publish/versioning
#IniOS,build-nameisusedasCFBundleShortVersionStringwhilebuild-numberisusedasCFBundleVersion.
#ReadmoreaboutiOSversioningat
#https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#InWindows,build-nameisusedasthemajor,minor,andpatchparts
#oftheproductandfileversionswhilebuild-numberisusedasthebuildsuffix.
version:1.0.0+1

environment:
sdk:'>=3.0.3<4.0.0'

#Dependenciesspecifyotherpackagesthatyourpackageneedsinordertowork.
#Toautomaticallyupgradeyourpackagedependenciestothelatestversions
#considerrunning`flutterpubupgrade--major-versions`.Alternatively,
#dependenciescanbemanuallyupdatedbychangingtheversionnumbersbelowto
#thelatestversionavailableonpub.dev.Toseewhichdependencieshavenewer
#versionsavailable,run`flutterpuboutdated`.
dependencies:
flutter:
sdk:flutter


#ThefollowingaddstheCupertinoIconsfonttoyourapplication.
#UsewiththeCupertinoIconsclassforiOSstyleicons.
cupertino_icons:^1.0.2

dev_dependencies:
flutter_test:
sdk:flutter

#The"flutter_lints"packagebelowcontainsasetofrecommendedlintsto
#encouragegoodcodingpractices.Thelintsetprovidedbythepackageis
#activatedinthe`analysis_options.yaml`filelocatedattherootofyour
#package.Seethatfileforinformationaboutdeactivatingspecificlint
#rulesandactivatingadditionalones.
flutter_lints:^2.0.0

#ForinformationonthegenericDartpartofthisfile,seethe
#followingpage:https://dart.dev/tools/pub/pubspec

#ThefollowingsectionisspecifictoFlutterpackages.
flutter:

#ThefollowinglineensuresthattheMaterialIconsfontis
#includedwithyourapplication,sothatyoucanusetheiconsin
#thematerialIconsclass.
uses-material-design:true

#Toaddassetstoyourapplication,addanassetssection,likethis:
#assets:
#-images/a_dot_burr.jpeg
#-images/a_dot_ham.jpeg

#Animageassetcanrefertooneormoreresolution-specific"variants",see
#https://flutter.dev/assets-and-images/#resolution-aware

#Fordetailsregardingaddingassetsfrompackagedependencies,see
#https://flutter.dev/assets-and-images/#from-packages

#Toaddcustomfontstoyourapplication,addafontssectionhere,
#inthis"flutter"section.Eachentryinthislistshouldhavea
#"family"keywiththefontfamilyname,anda"fonts"keywitha
#listgivingtheassetandotherdescriptorsforthefont.For
#example:
#fonts:
#-family:Schyler
#fonts:
#-asset:fonts/Schyler-Regular.ttf
#-asset:fonts/Schyler-Italic.ttf
#style:italic
#-family:TrajanPro
#fonts:
#-asset:fonts/TrajanPro.ttf
#-asset:fonts/TrajanPro_Bold.ttf
#weight:700
#
#Fordetailsregardingfontsfrompackagedependencies,
#seehttps://flutter.dev/custom-fonts/#from-packages
